Improve the error prompt when wgsl code is multi line error
pygfx/wgpu-py pull request #311
Opened 2022-12-19 08:42 UTC by panxinmiao

The previous error prompt did not consider the situation when the error code is multiple lines.
For example:

![image](https://user-images.githubusercontent.com/8044566/208381604-d0ba24e0-5db5-4aee-9a63-dcc4ae3ac04f.png)

It indicates that the error is at line 45, position -390, It is still difficult to quickly locate the wrong position.

This PR improves this, When the error is multiple lines, the code of error part and reason will be output directly, help locate quickly.

![image](https://user-images.githubusercontent.com/8044566/208382849-4e33d006-17a4-4f2c-9924-36ebeacea800.png)

2022-12-19 11:52 UTC, almarklein requested changes
Awesome! Could you please add a unit test for this case to avoid regressions?

2022-12-20 01:59 UTC, panxinmiao commented
> Awesome! Could you please add a unit test for this case to avoid regressions?

OK, unit test has been added.

2022-12-20 06:53 UTC, Korijn approved these changes

2022-12-20 08:27 UTC, almarklein approved these changes
Thanks!

2022-12-20 08:27 UTC, merged